#!/bin/bash

down() {
light -U 5
brightness=$(brillo -G | cut -d '.' -f1)
notify-send "BRIGHTNESS" "Screen backlight to $brightness%" -h int:value:"$brightness" -i display-brightness-symbolic -r 2593 -u normal
}

up() {
light -A 5
brightness=$(light -G | cut -d '.' -f1)
notify-send "BRIGHTNESS" "Screen backlight to $brightness%" -h int:value:"$brightness" -i display-brightness-symbolic -r 2593 -u normal
}

case "$1" in
  up) up;;
  down) down;;
esac
