#!/usr/bin/bash

function selection() {
    grim -g "$(slurp)" - | swappy -f - -o ~/Pictures/Screenshots/screenshot$(date +%s).png
}

function full_screen() {
    grim - | swappy -f - -o ~/Pictures/Screenshots/screenshot$(date +%s).png
}

function delay() {
    geo="$(slurp)"
    sleep 3
    grim -g "$geo" - | swappy -f - -o ~/Pictures/Screenshots/screenshot$(date +%s).png
}

doc() {
    echo "Usage:
    screenshot [Options]

    Options:
        selection       Screenshots the selected area
        full_screen     Screenshots the entire screen
        delay           Takes a screenshot of the selected area after 3 seconds"
}

case $1 in 
    selection) selection                ;;
    full_screen) full_screen            ;;
    delay) delay                        ;;
    *) doc                              ;;
esac
