#!/bin/bash

adjust_volume() {
    wpctl set-volume @DEFAULT_AUDIO_SINK@ "$1"
    volume=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print int($2*100)}')
    notify-send "VOLUME" "$2 to $volume%" -h int:value:"$volume" -i "$3" -r 2593 -u normal
}

toggle_mute() {
    if  wpctl get-volume @DEFAULT_AUDIO_SINK@ | grep -q '\[MUTED\]'; then
        wpctl set-mute @DEFAULT_AUDIO_SINK@ 0
        notify-send "VOLUME" "UNMUTED" -i audio-volume-high-symbolic -u normal
    else
        wpctl set-mute @DEFAULT_AUDIO_SINK@ 1
        notify-send "VOLUME" "MUTED" -i audio-volume-muted-symbolic -u normal
    fi
}

case "$1" in
    up) adjust_volume "5%+" "Increasing" "audio-volume-high-symbolic" ;;
    down) adjust_volume "5%-" "Decreasing" "audio-volume-low-symbolic" ;;
    mute) toggle_mute ;;
    *) echo "Usage: $0 {up|down|mute}" ;;
esac
