#!/bin/bash

# Get Volume
get_volume() {
    status=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | grep -wo 'MUTED')

    if [[ -z "$status" ]]; then
        volume=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print $2 * 100}' | cut -d. -f1)
        echo "$volume"
    else
        echo "Mute"
    fi
}

# Get icons
get_icon() {
    vol="$(get_volume)"
    status=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | grep -wo 'MUTED')

    if [[ -z "$status" ]]; then
        if [[ "$vol" -eq "0" ]]; then
            echo "ﱝ"
        elif [[ "$vol" -le "30" ]]; then
            echo "奄"
        elif [[ "$vol" -le "60" ]]; then
            echo "奔"
        elif [[ "$vol" -le "100" ]]; then
            echo "墳"
        fi
    else
        echo "ﱝ"
    fi
}

# Increase Volume
inc_volume() {
    wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
}

# Decrease Volume
dec_volume() {
    wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
}

# Toggle Mute
toggle_mute() {
    wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
    get_volume
elif [[ "$1" == "--icon" ]]; then
    get_icon
elif [[ "$1" == "--inc" ]]; then
    inc_volume
elif [[ "$1" == "--dec" ]]; then
    dec_volume
elif [[ "$1" == "--toggle" ]]; then
    toggle_mute
else
    get_volume
fi
